# Header
menu:
  主页: /               # 主页链接
#  标签: /tags
  归档: /archives   # 存档链接
#  友链: /friendLink
  关于: /about         # 关于链接
#rss: /atom.xml          # RSS链接
home:
  style: Not-detail        # 主页样式，默认或详细detail

favicon: https://img1.8jppeg.com/images/64acb6103389e89b4a1690f8.png                # 网站图标的路径（例如，如果你的网站图标文件位于/source/favicon.png，则为"/favicon.png"）

# Banner
banner:
  enable: true         # 显示横幅
  url: https://img1.8jppeg.com/images/64acb60c3389e89b4a168fd3.jpg    # 横幅图片的路径
  position: top      # 图片的对齐方式，参考CSS中的"object-position"属性
  onAllPages: true      # 在所有页面上显示横幅

# Appearence
hue: 250                # 主题颜色的色调（例如，红色: 0, 橙色: 60, 蓝色: 260, 紫色: 300, 粉色: 345）

# Sidebar
sidebar:
  widgets: # 启用的小部件（profile, category, tag, archive, recent_posts）
    normal: # 固定位置
      - profile #配置
      - announcement #公告
      - tag #标签
      - category #分类
    sticky: # 滚动与页面一起滚动
      - recent_posts #最新文章
      - archive #归档
      - aaa
#      - recent_posts #最新文章



# Widget behavior
archive_type: 'monthly'    # 存档页面按月份显示
recent_posts_limits: 5     # 显示的最近文章数量

# Personal info
avatar: https://img1.8jppeg.com/images/64acb6103389e89b4a1690f8.png                    # 作者头像
author: 浅笑笑笑           # 作者名称
subtitle: 轻舟已过万重山   # 副标题
announcement: 加载有点慢。多等等图标就加载出来了。。。不影响不影响 #公告
links: # 社交媒体链接
  - name: bilibili           # 链接名称
    icon: fa-brands fa-bilibili   # 链接的图标代码（参考：https://fontawesome.com/search）
    url: https://space.bilibili.com/59202265?spm_id_from=333.1007.0.0   # 链接地址
  - name: Steam
    icon: fa-brands fa-steam
    url: https://store.steampowered.com
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/dajavv

comment:
  valine:
    enable: false          # 启用评论功能（使用了Valine评论系统）
    appId:
    appKey:

# Local search
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # 如果没有查到内容相关内容显示

inject:
  head:
    - <link rel="stylesheet" href=" /css/custom.css">
  bottom:

